tasks:
  - init: pyenv install -f & pip install -r requirements.txt & pip install requests
    command: flask init & flask run




ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: true
